name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          git config --global user.email "jraines521@gmail.com"
          git config --global user.name "lorax521"
          git clone https://github.com/nhrap-dev/manage.git https://github.com/nhrap-dev/test-tool
          git remote add github "https://github.com/nhrap-dev/test-tool.git"
          git add -A
          git commit -m "manage update"
          git push
