name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          git clone https://github.com/nhrap-dev/test-tool.git
          cp ./manage.py ./test-tool/manage.py
          cd test-tool
          git add .
          git commit -m "update manage.py"
          git push origin master
          cd ..
          rm -rf test-tool
