name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          git remote test-tool add github "https://github.com/nhrap-dev/manage.git"
          git remote test-tool add -A
          git remote test-tool commit -m "manage update"
          git push test-tool
